
version: '3.9'

services:
  localRabbitMQ:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brt_db
#      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data/pgdata

