

services:
  localRabbitMQ:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672
  postgresBrt:
    image: postgres:latest
    container_name: postgres_brt
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: brt_db
    ports:
      - "5430:5432"
  postgresHrs:
      image: postgres:latest
      container_name: postgres_hrs
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: hrs_db
      ports:
        - "5440:5432"

