spring.application.name: NexignBootcampTestCase

nPools: 5

spring:

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: public
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    username: user
    password: password
    ports:
      - "5672:5672"
    template:
      queue: cdr_queue
      exchange: cdr_exchange
      routing-key: cdr_routing_key
  h2:
    console:
      enabled: true
      path: /h2-console