spring.application.name: brt

server:
  port: 8081


spring:
  datasource:
    #    platform: postgres
    url: "jdbc:postgresql://localhost:5430/brt_db"
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
    default-schema: public
  rabbitmq:
    username: user
    password: password
    ports:
      - "5672:5672"
    template:
      queue: cdr_queue
hrs:
  service:
    url: "http://localhost:8082"
